# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "hpsa" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#   fileSystems."/" =
#     { device = "/dev/disk/by-uuid/a28be87c-8eeb-4aa0-a4f3-15c7e8a4704b";
#       fsType = "ext4";
#     };
# 
#   fileSystems."/boot" =
#     { device = "/dev/disk/by-uuid/F0B3-41E1";
#       fsType = "vfat";
#       options = [ "fmask=0022" "dmask=0022" ];
#     };
# 
#   swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
