# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # TODO: WHY DOESN'T DISKO WORK?!?!

  fileSystems."/" =
    { device = lib.mkForce "/dev/disk/by-uuid/5cf16008-8c3b-4920-8c7b-6487318c8571";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = lib.mkForce "/dev/disk/by-uuid/14F2-6C0B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = lib.mkForce "/dev/disk/by-uuid/043afb9a-e8f7-44b6-8bc1-5802deb60af7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
