# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/242d3222-f0ad-4076-b259-769044e44d31";
#      fsType = "ext4";
#    };
#
#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/EF07-9D32";
#      fsType = "vfat";
#      options = [ "fmask=0077" "dmask=0077" ];
#    };
#
#  swapDevices =
#    [ { device = "/dev/disk/by-uuid/545b37e6-1473-43b3-bc88-8e92e4a5f68c"; }
#    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
