views:
  - title: Luci
    type: sections
    icon: mdi:lightbulb
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Salotto
            heading_style: title
            icon: mdi:sofa
            grid_options:
              columns: 12
              rows: 1
          - alert_classes:
              - motion
              - moisture
            sensor_classes:
              - temperature
              - humidity
            type: area
            area: salotto
          - type: tile
            entity: light.luce_salotto_est
          - type: tile
            entity: light.luce_salotto_ovest
          - type: tile
            entity: light.luce_salotto_sud
          - type: tile
            entity: light.luce_entrata
        column_span: 1
      - type: grid
        cards:
          - type: heading
            heading: Cucina
            heading_style: title
            icon: mdi:faucet-variant
          - alert_classes:
              - motion
              - moisture
            sensor_classes:
              - temperature
              - humidity
            type: area
            area: cucina
          - type: tile
            entity: light.luce_cucina_est
          - type: tile
            entity: light.luce_cucina_ovest
          - type: tile
            entity: light.luce_cucina_piano_lavoro
          - type: tile
            entity: light.luce_cucina_sud
      - type: grid
        cards:
          - type: heading
            heading: Bagno
            heading_style: title
            icon: mdi:bathtub
          - type: area
            area: bagno
          - type: tile
            entity: light.luce_bagno
          - type: tile
            entity: light.luce_bagno_specchio
      - type: grid
        cards:
          - type: heading
            heading: Cameretta
            heading_style: title
            icon: mdi:bed-single
          - alert_classes:
              - motion
              - moisture
            sensor_classes:
              - temperature
              - humidity
            type: area
            area: cameretta
          - type: tile
            entity: light.luce_cameretta
      - type: grid
        cards:
          - type: heading
            heading: Matrimoniale
            heading_style: title
            icon: mdi:bed-king
          - alert_classes:
              - motion
              - moisture
            sensor_classes:
              - temperature
              - humidity
            type: area
            area: matrimoniale
          - type: tile
            entity: light.luce_matrimoniale
          - type: tile
            entity: light.luce_matrimoniale_alto
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Altro
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.luce_corridoio
          - type: tile
            entity: light.luce_cucina_balcone
          - type: tile
            entity: light.luce_salotto_balcone_ovest
          - type: tile
            entity: light.luce_matrimoniale_balcone
          - type: tile
            entity: light.luce_salotto_balcone_est
            features_position: bottom
            vertical: false
            grid_options:
              columns: 6
              rows: 1
    header:
      card:
        type: markdown
        content: '# Controllo Luci'
    badges:
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: binary_sensor.display_local
        name: Display
        show_entity_picture: false
        state_content:
          - state
          - last_changed
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.uptime
        show_entity_picture: false
    cards: []
    max_columns: 2
    subview: false
  - type: sections
    max_columns: 2
    title: Tapparelle
    path: tapparelle
    icon: mdi:window-shutter
    sections:
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Salotto
            icon: mdi:sofa
          - type: entities
            entities:
              - entity: cover.tapparella_salotto_ovest_1
              - entity: cover.tapparella_salotto_ovest_2
              - entity: cover.tapparella_salotto_sud
            show_header_toggle: true
            grid_options:
              columns: full
        column_span: 1
      - type: grid
        cards:
          - type: heading
            heading: Cucina
            heading_style: title
            icon: mdi:faucet-variant
          - type: entities
            entities:
              - entity: cover.tapparella_cucina_est
              - entity: cover.tapparella_cucina_sud
            grid_options:
              columns: full
            show_header_toggle: true
        column_span: 1
      - type: grid
        cards:
          - type: heading
            heading: Bagno
            heading_style: title
            icon: mdi:bathtub
          - type: entities
            entities:
              - entity: cover.tapparella_bagno
            show_header_toggle: true
            state_color: false
            grid_options:
              columns: full
      - type: grid
        cards:
          - type: heading
            heading: Cameretta
            heading_style: title
            icon: mdi:bed-single
          - type: entities
            entities:
              - entity: cover.tapparella_cameretta_est
              - entity: cover.tapparella_cameretta_nord
            grid_options:
              columns: full
            show_header_toggle: true
      - type: grid
        cards:
          - type: heading
            heading: Matrimoniale
            heading_style: title
            icon: mdi:bed-double
          - type: entities
            entities:
              - entity: cover.tapparella_matrimoniale
            grid_options:
              columns: full
            show_header_toggle: true
    header:
      card:
        type: markdown
        content: '# Controllo Tapparelle'
    cards: []
    badges:
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: binary_sensor.display_local
        name: Display
        show_entity_picture: false
        state_content:
          - state
          - last_changed
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.uptime
        show_entity_picture: false
  - type: sections
    max_columns: 2
    title: Termostato
    path: termostato
    icon: mdi:thermostat
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Stanze
            heading_style: title
            icon: mdi:texture-box
          - type: thermostat
            entity: climate.termostato_soggiorno
            show_current_as_primary: true
          - type: thermostat
            entity: climate.termostato_bagno
            show_current_as_primary: true
        column_span: 1
      - type: grid
        cards:
          - type: heading
            heading: Camere
            heading_style: title
            icon: mdi:bed-king
          - type: thermostat
            entity: climate.termostato_matrimoniale
            show_current_as_primary: true
          - type: thermostat
            entity: climate.termostato_cameretta
            show_current_as_primary: true
    header:
      card:
        type: markdown
        content: '# Controllo Termostato'
    cards: []
    badges:
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: binary_sensor.display_local
        name: Display
        show_entity_picture: false
        state_content:
          - state
          - last_changed
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.uptime
        show_entity_picture: false
  - type: sections
    max_columns: 2
    icon: mdi:gauge
    path: ''
    visible:
      - user: d35ec065e1c14502924b0822b389c5c3
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Power
            heading_style: title
            icon: mdi:power-plug
          - type: tile
            entity: binary_sensor.rpi_power_status
            features_position: bottom
            vertical: false
            grid_options:
              columns: 12
              rows: 1
            name: Power Supply
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Connectivity
            icon: mdi:electric-switch
          - type: tile
            entity: sensor.system_monitor_ipv4_address_enu1u1
            features_position: bottom
            vertical: false
            grid_options:
              columns: 12
              rows: 1
            name: enu1u1
            hide_state: false
            show_entity_picture: false
        column_span: 1
      - type: grid
        cards:
          - type: heading
            icon: mdi:memory
            heading: Processor
            heading_style: title
          - chart_type: line
            period: 5minute
            type: statistics-graph
            entities:
              - sensor.system_monitor_load_1_min
              - sensor.system_monitor_processor_use
            stat_types:
              - mean
              - max
              - min
            title: CPU Load
            logarithmic_scale: false
            hide_legend: false
            days_to_show: 1
          - graph: line
            type: sensor
            entity: sensor.system_monitor_processor_temperature
            detail: 2
            name: CPU Temperature
            grid_options:
              columns: 12
              rows: 2
            hours_to_show: 24
            limits:
              min: 35
              max: 100
      - type: grid
        cards:
          - type: heading
            icon: mdi:sd
            heading: Memory
            heading_style: title
          - chart_type: line
            period: 5minute
            type: statistics-graph
            entities:
              - sensor.system_monitor_memory_use
              - sensor.system_monitor_swap_use
            stat_types:
              - mean
              - max
              - min
            title: RAM
            days_to_show: 1
          - type: gauge
            entity: sensor.system_monitor_memory_usage
            needle: true
            severity:
              green: 0
              yellow: 70
              red: 90
            name: RAM Usage
            grid_options:
              columns: 6
              rows: auto
          - type: gauge
            entity: sensor.system_monitor_swap_usage
            name: Swap Usage
            needle: true
            severity:
              green: 0
              yellow: 40
              red: 80
            grid_options:
              columns: 6
              rows: auto
    header:
      card:
        type: markdown
        content: '# System Status'
    badges:
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: binary_sensor.display_local
        name: Display
        show_entity_picture: false
        state_content:
          - state
          - last_changed
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.uptime
        show_entity_picture: false
    cards: []
  - type: sections
    max_columns: 2
    title: Devices
    path: devices
    icon: mdi:devices
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Availability
            heading_style: title
            icon: mdi:link-variant
          - type: history-graph
            entities:
              - entity: binary_sensor.quiss_server_local
              - entity: binary_sensor.msi_host_local
              - entity: binary_sensor.display_local
            title: History
            logarithmic_scale: false
            grid_options:
              columns: 12
              rows: 4
          - type: tile
            features_position: bottom
            vertical: false
            entity: binary_sensor.quiss_server_local
          - type: tile
            features_position: bottom
            vertical: false
            entity: binary_sensor.msi_host_local
          - type: heading
            heading: Wake
            heading_style: title
            icon: mdi:lightning-bolt
          - type: tile
            entity: switch.quiss
            features_position: bottom
            vertical: false
          - type: tile
            entity: switch.msi
            features_position: bottom
            vertical: false
      - type: grid
        cards:
          - type: heading
            heading_style: title
            icon: mdi:cctv
            heading: Cameras
          - type: custom:webrtc-camera
            title: NerioGoPro2
            url: gopro
            muted: true
            ui: true
    header:
      card:
        type: markdown
        content: '# Devices'
    visible:
      - user: d35ec065e1c14502924b0822b389c5c3
    cards: []
    badges:
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: binary_sensor.display_local
        name: Display
        show_entity_picture: false
        state_content:
          - state
          - last_changed
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.uptime
        show_entity_picture: false
